/*
 * Academy curriculum. Each lesson is HTML plus an optional quiz.
 * <div data-widget="name"></div> mounts an interactive widget (academy.js).
 * <a data-goto="tab"> links jump to another tab of the app.
 */
window.LRPS_ACADEMY = [
  // =====================================================================
  {
    id: 'foundations',
    title: 'Ballistics foundations',
    lessons: [
      {
        id: 'what-is-dope',
        title: 'What a dope card really is',
        mins: 4,
        html: `
<div class="callout rule"><b>Rule:</b> A bullet's path is fully determined by a handful of inputs. A dope card is that physics
<b>precomputed</b> into a lookup table so that, under time pressure, you only do a lookup and a small adjustment.</div>
<p>"DOPE" is usually expanded as <i>Data On Previous Engagements</i>: originally it was literally a record of what worked.
Today the card is generated by a ballistic solver and then <b>verified</b> against real impacts.</p>
<h4>The three ballistics</h4>
<table class="tbl text">
<thead><tr><th>Phase</th><th>Where</th><th>What it decides</th><th>Your lever</th></tr></thead>
<tbody>
<tr><td>Internal</td><td>Chamber → muzzle</td><td>Muzzle velocity (MV) and its consistency (SD)</td><td>Ammo, barrel, powder temperature</td></tr>
<tr><td>External</td><td>Muzzle → target</td><td>Drop, wind drift, time of flight</td><td><b>The dope card</b></td></tr>
<tr><td>Terminal</td><td>At the target</td><td>Energy, expansion, steel ring/no ring</td><td>Bullet choice, impact velocity</td></tr>
</tbody></table>
<h4>The system as code</h4>
<pre class="code">inputs  = { MV, BC + drag model, sight height, zero, twist,      // fixed per rifle/load
            range, wind, density altitude, shot angle }         // vary per shot
outputs = { elevation, windage, time of flight, velocity }
card    = precompute(solver, ranges, typical_conditions)       // at home
shot    = adjust(lookup(card, range), wind_call, conditions)   // on the line</pre>
<div class="callout try"><b>Verify:</b> open the <a data-goto="lab">Lab</a>, drag the range-relevant sliders, and
predict the change before you look. If your predictions are wrong, the model in your head is wrong — that's what this Academy fixes.</div>`,
        quiz: [
          { q: 'Which phase of ballistics does the dope card describe?', options: ['Internal', 'External', 'Terminal'], answer: 1, why: 'External ballistics is the flight from muzzle to target: drop, drift and time of flight.' },
          { q: 'Where does a modern dope card come from?', options: ['Memorised rules of thumb', 'A solver, then verified against real impacts', 'The ammo box'], answer: 1, why: 'Solve first, then true it with live fire. The box numbers are a starting point at best.' },
        ],
      },
      {
        id: 'gravity-tof',
        title: 'Gravity, time of flight and the trajectory',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> Gravity pulls the bullet down for exactly as long as it is in the air.
<b>Drop is a function of time of flight (TOF)</b>, and TOF grows faster than range because the bullet keeps slowing down.</div>
<p>In a vacuum, drop = ½·g·t². Real bullets slow down, so each successive 100 yards takes longer than the last, and the drop curve bends
increasingly steeply. That is why elevation at 1000 yd is not twice the value at 500 yd — it's typically 3×.</p>
<h4>Line of sight, bore line and zero</h4>
<ul>
<li>The scope sits <b>above</b> the bore (sight height, ~1.5–2.5"). The bore is tilted slightly up so the bullet crosses the line of sight at the <b>zero range</b>.</li>
<li>Relative to the line of sight, the bullet starts <i>below</i> it, rises to cross it, peaks, and falls back through it at the zero. The bullet never rises above the <i>bore line</i> — "rise" is purely relative to your sight line.</li>
<li>Inside ~50 yd you must hold <i>over</i> because the bullet is still below the line of sight (sight-height offset).</li>
</ul>
<table class="tbl text">
<thead><tr><th>Choice</th><th>Effect</th><th>Common pick</th></tr></thead>
<tbody>
<tr><td>100 yd zero</td><td>Easy to verify, small conditions sensitivity, clean card math</td><td>Precision / PRS</td></tr>
<tr><td>200 yd zero</td><td>Less dialing at mid range, more sensitive to zero errors</td><td>Hunting</td></tr>
<tr><td>Sight height</td><td>Measure center of bore → center of scope. A 0.5" error shifts close-range dope noticeably</td><td>Measure, don't guess</td></tr>
</tbody></table>
<div class="callout try"><b>Verify:</b> in the <a data-goto="lab">Lab</a> set the zero to 200 yd. The bullet path chart moves up — but the bullet's actual flight didn't change, only your reference line.</div>`,
        quiz: [
          { q: 'Why is elevation at 1000 yd much more than double that at 500 yd?', options: ['Gravity is stronger far away', 'The bullet slows, so TOF grows faster than range', 'The scope loses accuracy'], answer: 1, why: 'Drop depends on time of flight. Deceleration makes TOF grow faster than distance.' },
          { q: 'At 25 yd with a 100 yd zero, the bullet is…', options: ['Above the line of sight', 'Below the line of sight', 'Exactly on it'], answer: 1, why: 'It starts sight-height below the line of sight and has not yet climbed to cross it.' },
        ],
      },
      {
        id: 'drag-bc',
        title: 'Drag, BC and G1 vs G7',
        mins: 6,
        html: `
<div class="callout rule"><b>Rule:</b> Drag depends on the bullet's shape and its <b>Mach number</b>. A drag model (G1, G7) is the drag curve of
a reference projectile; the <b>ballistic coefficient (BC)</b> scales that curve to your bullet. Higher BC = less deceleration.</div>
<pre class="code">deceleration = air_density × v² × Cd(Mach) × π/8 / (BC × 703.07)   // BC in lb/in²</pre>
<div data-widget="drag-curves"></div>
<table class="tbl text">
<thead><tr><th>Model</th><th>Reference shape</th><th>Fits</th><th>Consequence</th></tr></thead>
<tbody>
<tr><td>G1</td><td>Flat base, short ogive (1880s artillery shape)</td><td>Hunting bullets, flat base</td><td>A modern boat-tail's G1 BC changes with velocity, so vendors publish several "stepped" G1 BCs</td></tr>
<tr><td>G7</td><td>Long boat-tail, secant ogive</td><td>Modern long-range match bullets</td><td>One G7 BC fits across most of the velocity range — prefer it</td></tr>
<tr><td>Custom drag curve</td><td>Your actual bullet, measured by Doppler radar</td><td>Everything</td><td>Best of all (Applied Ballistics, Hornady 4DOF libraries)</td></tr>
</tbody></table>
<div class="callout warn"><b>Exception:</b> a G1 and a G7 BC are <i>not</i> comparable numbers. 0.505 G1 and 0.243 G7 describe roughly the same .308 bullet.
Never put a G1 number in a G7 field.</div>
<div class="callout try"><b>Verify:</b> on <a data-goto="build">Build Card</a>, change BC by +0.02 and watch the 1000 yd elevation tile, then do the same at 300 yd. BC barely matters close in.</div>`,
        quiz: [
          { q: 'Which drag model best fits a modern boat-tail match bullet?', options: ['G1', 'G7', 'Either, the BC number is the same'], answer: 1, why: 'G7 is a long boat-tail shape, so one G7 BC holds across velocities.' },
          { q: 'A bullet has BC 0.50 G1. Its G7 BC is about…', options: ['0.50', '0.25', '1.00'], answer: 1, why: 'G7 BCs are roughly half the G1 number for modern bullets. They are different scales.' },
          { q: 'Raising BC by 0.02 changes elevation most at…', options: ['200 yd', '1000 yd', 'Equally at all ranges'], answer: 1, why: 'BC acts through accumulated deceleration, which only adds up over long flight times.' },
        ],
      },
      {
        id: 'transonic',
        title: 'Velocity, Mach and the transonic zone',
        mins: 4,
        html: `
<div class="callout rule"><b>Rule:</b> Around Mach 1 (≈1,120 fps, varies with temperature) the drag coefficient spikes and the airflow becomes unsteady.
Predictions get worse and some bullets lose stability. Treat <b>Mach 1.2 (~1,340 fps)</b> as the edge of trustworthy solver data.</div>
<table class="tbl text">
<thead><tr><th>Regime</th><th>Mach</th><th>What happens</th><th>On your card</th></tr></thead>
<tbody>
<tr><td>Supersonic</td><td>&gt; 1.2</td><td>Drag behaves; solver is reliable</td><td>Normal rows</td></tr>
<tr><td>Transonic</td><td>0.8 – 1.2</td><td>Drag spike, shock waves pass over the bullet, dispersion can open up</td><td>Mark rows, true with field data</td></tr>
<tr><td>Subsonic</td><td>&lt; 0.8–1.0</td><td>Steady again, but bullet may tumble if marginally stable</td><td>Mark "limit"</td></tr>
</tbody></table>
<p>The speed of sound rises with temperature (~1,087 fps at 32°F, ~1,150 fps at 90°F). So the transonic threshold is a
<i>moving target</i>: on a hot day Mach 1.2 is a higher fps number, while the thinner hot air also slows the bullet less.
Your solver handles both — just give it the real temperature.</p>
<div class="callout try"><b>Verify:</b> the shaded band on the <a data-goto="lab">Lab</a> charts is the transonic zone. Raise MV or BC and watch it slide out.</div>`,
        quiz: [
          { q: 'A practical edge for "trust the solver" is…', options: ['Mach 2.0', 'Mach 1.2', 'Mach 0.5'], answer: 1, why: 'Below roughly Mach 1.2 the drag curve changes quickly and predictions need field truing.' },
        ],
      },
      {
        id: 'atmosphere',
        title: 'The atmosphere and density altitude',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> Drag is proportional to air density. Temperature, pressure and humidity collapse into one number:
<b>density altitude (DA)</b> — the altitude in a standard atmosphere that has the same air density. Higher DA = thinner air = less drop.</div>
<table class="tbl text">
<thead><tr><th>Change</th><th>Air density</th><th>Effect on elevation</th></tr></thead>
<tbody>
<tr><td>Hotter</td><td>Lower</td><td>Less (and hot powder may add MV too)</td></tr>
<tr><td>Higher elevation / lower pressure</td><td>Lower</td><td>Less</td></tr>
<tr><td>More humid</td><td>Slightly lower (water vapour is lighter than air)</td><td>Tiny — usually negligible</td></tr>
</tbody></table>
<p>Rough sensitivity: ~0.15 mil per 1,000 ft of DA at 1000 yd for a 6.5 Creedmoor. Every 1,000 ft of DA is roughly 3% less air.</p>
<div data-widget="density-altitude"></div>
<div class="callout warn"><b>Exception:</b> use <b>station pressure</b> (what a barometer reads where you are), not the "sea-level corrected"
pressure from a weather report. Using corrected pressure at a mountain range makes the solver think you are at sea level.</div>`,
        quiz: [
          { q: 'A hot afternoon at a mountain range has ___ density altitude than a cold morning at the coast.', options: ['Lower', 'Higher', 'The same'], answer: 1, why: 'Heat and altitude both thin the air, which raises density altitude.' },
          { q: 'Which pressure belongs in a ballistic solver?', options: ['Station (absolute) pressure', 'Sea-level corrected pressure from the news'], answer: 0, why: 'The bullet flies through the air where you are, at its real pressure.' },
        ],
      },
      {
        id: 'wind',
        title: 'Wind: lag time, value and direction',
        mins: 6,
        html: `
<div class="callout rule"><b>Rule:</b> Wind drift is set by <b>lag time</b> — how much longer the bullet takes than it would in a vacuum:
<code>drift = crosswind × (TOF − range / MV)</code>. Only the <b>crosswind component</b> counts.</div>
<p>This is why a high-BC bullet drifts less: it loses less speed, so its lag time is smaller. It also explains why drift is almost linear in wind
speed — double the wind, double the drift.</p>
<h4>Wind value (clock system)</h4>
<p>Target is 12 o'clock. The fraction of the wind that pushes sideways is <code>|sin(clock × 30°)|</code>.</p>
<div data-widget="wind-clock"></div>
<table class="tbl text">
<thead><tr><th>From</th><th>Value</th><th>Name</th></tr></thead>
<tbody>
<tr><td>3 or 9</td><td>1.0</td><td>Full value</td></tr>
<tr><td>2, 4, 8, 10</td><td>≈ 0.87 (treat as full)</td><td>"Near full"</td></tr>
<tr><td>1:30, 4:30, 7:30, 10:30</td><td>≈ 0.7</td><td>¾ value</td></tr>
<tr><td>1, 5, 7, 11</td><td>0.5</td><td>Half value</td></tr>
<tr><td>12 or 6</td><td>0</td><td>No value (head/tail — tiny elevation effect)</td></tr>
</tbody></table>
<div class="callout warn"><b>Exception:</b> wind is rarely one number. The bullet integrates every gust along its path, and the wind at the
target can blow the opposite way to the wind at your position. You call a <i>bracket</i> and hold for its middle (or for the plate edge).</div>
<div class="callout try"><b>Verify:</b> drill it in <a data-goto="drill">Drills → Wind call</a>, then read real flags on the <a data-goto="range">Range</a>.</div>`,
        quiz: [
          { q: 'A 10 mph wind from 1 o\'clock has the same drift as…', options: ['10 mph full value', '5 mph full value', '0 mph'], answer: 1, why: 'sin(30°) = 0.5, so it is half value.' },
          { q: 'Why does a high-BC bullet drift less in the same wind?', options: ['It is heavier', 'Less lag time: it loses less speed', 'It spins faster'], answer: 1, why: 'Drift is proportional to lag time, which a low-drag bullet minimises.' },
        ],
      },
      {
        id: 'small-effects',
        title: 'Spin drift, Coriolis and aerodynamic jump',
        mins: 6,
        html: `
<div class="callout rule"><b>Rule:</b> Three second-order effects add up to a few tenths of a mil at 1000 yd. Individually small, together
they can turn an edge hit into a miss on a small plate.</div>
<table class="tbl text">
<thead><tr><th>Effect</th><th>Cause</th><th>Direction</th><th>Typical size @1000 yd</th></tr></thead>
<tbody>
<tr><td>Spin drift</td><td>The spinning bullet's nose points slightly right of its path (right twist) — "yaw of repose"</td><td>Right for right twist, grows with TOF</td><td>0.1–0.3 mil</td></tr>
<tr><td>Coriolis (horizontal)</td><td>Earth rotates under the bullet</td><td>Right in northern hemisphere, left in southern</td><td>~0.05–0.1 mil</td></tr>
<tr><td>Coriolis (vertical, Eötvös)</td><td>Firing east adds to Earth's rotation, west subtracts</td><td>East = high, West = low</td><td>~0.05 mil</td></tr>
<tr><td>Aerodynamic jump</td><td>A crosswind tips the spinning bullet as it leaves the muzzle</td><td>Right twist: wind from left = high, from right = low</td><td>~0.1 mil per 10 mph</td></tr>
</tbody></table>
<div data-widget="coriolis"></div>
<div class="callout tip"><b>Practical:</b> many shooters fold spin drift into their wind zero (e.g. "hold 0.1 L at 800, 0.2 L at 1000 in no wind").
Coriolis matters at extreme range or for small targets; your solver handles it if you give it latitude and azimuth.</div>`,
        quiz: [
          { q: 'In the northern hemisphere, Coriolis pushes the bullet…', options: ['Left', 'Right', 'Only up'], answer: 1, why: 'Northern hemisphere deflection is to the right regardless of direction.' },
          { q: 'Right-twist barrel, wind from the right (3 o\'clock). Aerodynamic jump sends the shot…', options: ['High', 'Low', 'Nowhere'], answer: 1, why: 'For right twist: wind from left = high, wind from right = low.' },
        ],
      },
      {
        id: 'stability',
        title: 'Stability and twist rate',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> A bullet is gyroscopically stable when its spin overpowers the aerodynamic force trying to flip it.
The <b>stability factor Sg</b> (Miller formula) captures this: <b>&lt; 1.0 unstable · 1.0–1.4 marginal · &gt; 1.4 good · ~1.5+ for full BC</b>.</div>
<pre class="code">Sg = 30·m / (t² · d³ · l · (1 + l²)) × (V/2800)^(1/3) × (T+460)/519 × 29.92/P
m = weight (gr)   d = diameter (in)   l = length (calibers)   t = twist (calibers)</pre>
<div data-widget="stability"></div>
<ul>
<li><b>Longer bullets need faster twist</b> — length matters more than weight. Monolithic copper bullets are long for their weight.</li>
<li>Marginal stability <b>lowers the effective BC</b> and widens groups, especially in cold, dense air.</li>
<li>Over-stabilisation (Sg 3+) is mostly harmless for match bullets.</li>
</ul>`,
        quiz: [
          { q: 'Sg of 1.2 means…', options: ['Unstable', 'Marginal — may lose BC, especially in cold air', 'Ideal'], answer: 1, why: 'Between 1.0 and 1.4 is marginal. Cold, dense air lowers Sg further.' },
          { q: 'Which matters more for required twist?', options: ['Bullet weight', 'Bullet length', 'Case capacity'], answer: 1, why: 'The Miller formula depends strongly on length in calibers.' },
        ],
      },
    ],
  },
  // =====================================================================
  {
    id: 'optics',
    title: 'Optics & angular units',
    lessons: [
      {
        id: 'mil-moa',
        title: 'Think in angles: the milliradian (MIL)',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> Scopes adjust in <b>angles</b>, not inches. An angle covers more inches the farther you look, so one
number works at every range. This app — like most precision shooters, PRS competitors and military snipers — uses the
<b>milliradian (MIL)</b> for reticle, turrets, card and spotter calls.</div>
<table class="tbl text">
<thead><tr><th>Distance</th><th>1 MIL covers</th><th>0.1 MIL (one click) covers</th></tr></thead>
<tbody>
<tr><td>100 yd</td><td>3.6 in</td><td>0.36 in</td></tr>
<tr><td>500 yd</td><td>18 in</td><td>1.8 in</td></tr>
<tr><td>1000 yd</td><td>36 in</td><td>3.6 in</td></tr>
<tr><td>100 m</td><td>10 cm</td><td>1 cm</td></tr>
</tbody></table>
<pre class="code">inches = mils × 3.6 × (yards / 100)
mils   = inches / (3.6 × yards / 100)
clicks = mils / 0.1</pre>
<div data-widget="unit-converter"></div>
<div class="callout tip"><b>Why MIL won:</b> decimal math under stress ("up 0.3"), the same unit for holds, ranging and corrections, and spotters
call in mils. Most long-range first-focal-plane scopes are sold as MIL/MIL.</div>
<div class="callout warn"><b>You will still hear "MOA"</b> (minute of angle, ≈ 0.29 mil). Older scopes, hunting and benchrest use it, and some
parts are named after it (a "20 MOA" scope base). The one rule: never mix units between reticle, turrets and card.</div>`,
        quiz: [
          { q: '0.5 mil at 600 yd is how many inches?', options: ['3.0', '10.8', '18.0'], answer: 1, why: '0.5 × 3.6 × 6 = 10.8 in.' },
          { q: 'A 12" plate at 800 yd measures how many mils?', options: ['0.42', '0.6', '1.5'], answer: 0, why: '12 / (3.6 × 8) = 0.417 mil.' },
          { q: 'You need 2.3 mil of elevation. How many clicks?', options: ['2.3', '23', '230'], answer: 1, why: '2.3 / 0.1 = 23 clicks.' },
        ],
      },
      {
        id: 'reticles',
        title: 'Reticles: FFP vs SFP and reticle styles',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> In a <b>first focal plane (FFP)</b> scope the reticle grows and shrinks with the image, so its subtensions are
correct at every magnification. In a <b>second focal plane (SFP)</b> scope they are correct only at one magnification (usually max).</div>
<table class="tbl text">
<thead><tr><th></th><th>FFP</th><th>SFP</th></tr></thead>
<tbody>
<tr><td>Holds/ranging</td><td>Valid at any power</td><td>Only at the calibrated power</td></tr>
<tr><td>Look at low power</td><td>Reticle tiny</td><td>Reticle stays bold</td></tr>
<tr><td>Typical use</td><td>Precision, PRS, tactical</td><td>Hunting, benchrest, budget</td></tr>
</tbody></table>
<h4>Reticle styles</h4>
<ul>
<li><b>Hash/duplex mil reticles</b> — marks every 0.5 or 1 mil on the axes. Clean, good for dialing shooters.</li>
<li><b>"Christmas tree" reticles</b> — a grid of holdover points below center for holding elevation and wind together without dialing. Fast for stages with many distances.</li>
<li><b>Floating center / open center</b> — less clutter on small targets, easier to see your impact.</li>
</ul>
<div class="callout tip"><b>Dial elevation, hold wind</b> is the common precision workflow: elevation is predictable (dial it), wind changes second to second (hold it).</div>`,
        quiz: [
          { q: 'You mil a target on an SFP scope at half its max power. The reading is…', options: ['Correct', 'Wrong by a factor of 2', 'Wrong by 0.1 mil'], answer: 1, why: 'SFP subtensions scale with magnification; at half power each mark covers twice the angle.' },
          { q: 'The common precision workflow is…', options: ['Hold elevation, dial wind', 'Dial elevation, hold wind', 'Hold everything'], answer: 1, why: 'Elevation is stable once ranged; wind changes constantly, so holding it keeps you flexible.' },
        ],
      },
      {
        id: 'turrets',
        title: 'Turrets, revolutions and tracking',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> Turrets only help if they move the reticle by <b>exactly</b> what they say, every time, and you always know which
revolution you're on. Verify both before trusting a card.</div>
<table class="tbl text">
<thead><tr><th>Feature</th><th>Why it matters</th></tr></thead>
<tbody>
<tr><td>Click value</td><td>0.1 mil. Your card's "clicks" column depends on it.</td></tr>
<tr><td>Mils per revolution</td><td>10 mil/rev is common. At 12 mil of elevation you're on rev 2 — a classic 10-mil miss if you lose track.</td></tr>
<tr><td>Zero stop</td><td>Lets you spin back to zero blind. Set it after confirming zero.</td></tr>
<tr><td>Rev indicator</td><td>Pop-up pin or lines showing which revolution you're on.</td></tr>
<tr><td>Total travel</td><td>Long-range rifles often need a canted base (≈6 mil, sold as "20 MOA") to reach 1,000+ yd.</td></tr>
</tbody></table>
<h4>Tall target test (tracking)</h4>
<ol>
<li>At a measured 100 yd, hang a tall target with a plumb line.</li>
<li>Fire a group at zero, dial up e.g. 10 mil, fire again aiming at the same point.</li>
<li>Expected separation = 10 × 3.6 = 36.0". Measure. 35.3" means the scope moves ~2% less than labelled — scale your card (or the solver's "click correction").</li>
</ol>`,
        quiz: [
          { q: 'A tall target test shows 34.9" for 10 mil at a measured 100 yd. The scope tracks…', options: ['Perfectly', '~3% short', '~3% long'], answer: 1, why: '36.0" was expected; 34.9/36 = 0.97.' },
          { q: 'Why is a canted (≈6 mil) scope base common on long-range rifles?', options: ['Looks', 'More usable elevation travel', 'Better eye relief'], answer: 1, why: 'It pre-tilts the scope so more internal travel is available for elevation.' },
        ],
      },
      {
        id: 'mil-ranging',
        title: 'Ranging with the reticle',
        mins: 4,
        html: `
<div class="callout rule"><b>Rule (mil relation):</b> <code>range (yd) = size (in) × 27.78 / size (mil)</code>.
Metric: <code>range (m) = size (mm) / mils</code>.</div>
<div data-widget="mil-ranging"></div>
<table class="tbl text">
<thead><tr><th>Error source</th><th>Effect</th></tr></thead>
<tbody>
<tr><td>0.1 mil reading error on a small target</td><td>Huge: a 12" plate at 600 yd is 0.56 mil; reading 0.5 gives 667 yd</td></tr>
<tr><td>Wrong assumed target size</td><td>Proportional range error</td></tr>
<tr><td>SFP scope not at calibrated power</td><td>Wrong by the magnification ratio</td></tr>
</tbody></table>
<div class="callout tip">Measure the <b>largest</b> dimension you can, at max magnification, braced. Use a laser rangefinder whenever allowed — reticle ranging is the backup.</div>
<div class="callout try"><b>Verify:</b> turn off the rangefinder in <a data-goto="range">Range → settings</a> and mil the plates yourself.</div>`,
        quiz: [
          { q: 'An 18" target measures 0.8 mil. Range?', options: ['400 yd', '625 yd', '900 yd'], answer: 1, why: '18 × 27.78 / 0.8 = 625 yd.' },
        ],
      },
      {
        id: 'scope-setup',
        title: 'Scope setup: level, cant, parallax',
        mins: 4,
        html: `
<div class="callout rule"><b>Rule:</b> The reticle must be <b>square to gravity</b> and <b>parallax-free</b>, or the turrets move the shot somewhere other than where you think.</div>
<table class="tbl text">
<thead><tr><th>Setup item</th><th>Error if wrong</th><th>Fix</th></tr></thead>
<tbody>
<tr><td>Reticle level to the rifle</td><td>Elevation dial adds horizontal error</td><td>Level the action, then the reticle (plumb line)</td></tr>
<tr><td>Rifle cant while shooting</td><td>Cant × elevation = sideways miss: 2° with 10 mil dialed ≈ 0.35 mil horizontal</td><td>Scope-mounted bubble level, check every shot</td></tr>
<tr><td>Parallax</td><td>Reticle "floats" on target when your eye moves → apparent aim error</td><td>Adjust parallax until the reticle stays fixed</td></tr>
<tr><td>Eye relief / head position</td><td>Scope shadow, inconsistent sight picture</td><td>Same cheek weld every time</td></tr>
<tr><td>Ring torque</td><td>Scope slip under recoil, damaged tube</td><td>Torque wrench to spec</td></tr>
</tbody></table>
<pre class="code">horizontal error ≈ dialed_elevation × sin(cant)
10 mil dialed, 2° cant → 10 × 0.035 = 0.35 mil  (≈ 12" at 1000 yd)</pre>
<div class="callout try"><b>Verify:</b> enable "Cant & bubble level" on the <a data-goto="range">Range</a> and shoot a far target without leveling first.</div>`,
        quiz: [
          { q: 'You have 8 mil dialed and the rifle is canted 3° right. The shot lands roughly…', options: ['0.4 mil right', '0.4 mil left', 'On target'], answer: 0, why: '8 × sin(3°) ≈ 0.42 mil, towards the cant direction.' },
        ],
      },
    ],
  },
  // =====================================================================
  {
    id: 'cards',
    title: 'Writing a dope card',
    lessons: [
      {
        id: 'workflow',
        title: 'The workflow: from chronograph to card',
        mins: 6,
        html: `
<div class="callout rule"><b>Rule:</b> Garbage in, garbage out. The card is only as good as the <b>measured</b> inputs, and only trustworthy after it has been
<b>verified</b> at distance.</div>
<ol class="steps">
<li><b>Measure muzzle velocity.</b> Chronograph 10+ rounds of the exact ammo lot. Record average, SD, and the ammo temperature.</li>
<li><b>Collect the rest of the inputs.</b> Bullet BC (G7, or a custom drag model), bullet length and twist (for stability/spin drift), measured sight height, scope click value.</li>
<li><b>Zero precisely.</b> 100 yd, 5-shot groups, good conditions. Set the zero stop. Record zero conditions.</li>
<li><b>Solve.</b> Enter the data in a solver at the density altitude you expect to shoot in.</li>
<li><b>True the data.</b> Shoot at long range (e.g. 600–1000 yd). Adjust MV (and later BC/drop scale) until predictions match impacts.</li>
<li><b>Format the card.</b> Ranges in steps that fit your targets, elevation rounded to clicks, wind brackets, transonic marked, header with conditions.</li>
<li><b>Maintain.</b> Log every string in a data book; re-chrono when you change lots, and as the barrel wears.</li>
</ol>
<div class="callout try"><b>Do it:</b> step 4 and 6 happen on <a data-goto="build">Build Card</a>; step 5 is "truing mode" on the <a data-goto="range">Range</a>.</div>`,
        quiz: [
          { q: 'Which input most often makes a fresh card wrong?', options: ['Muzzle velocity from the ammo box', 'Gravity', 'Scope color'], answer: 0, why: 'Box MV comes from a different barrel length and conditions. Chronograph your own.' },
          { q: 'When is a card "trustworthy"?', options: ['After printing', 'After it has been verified/trued at distance', 'When it uses G7'], answer: 1, why: 'Only live fire at distance closes the loop between model and reality.' },
        ],
      },
      {
        id: 'anatomy',
        title: 'Anatomy of a good card',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> A card is a user interface for a stressed brain. Every column must be readable in a second, in your scope's unit,
already rounded to something you can dial.</div>
<div data-widget="card-anatomy"></div>
<table class="tbl text">
<thead><tr><th>Element</th><th>Why</th></tr></thead>
<tbody>
<tr><td>Header: load, MV, zero, DA/temp, unit</td><td>So you know when the card is valid and which rifle it belongs to</td></tr>
<tr><td>Range steps</td><td>50 yd to ~600, 25 yd beyond (the curve bends faster than you can interpolate)</td></tr>
<tr><td>Elevation in clicks <i>and</i> units</td><td>Units for holds and spotter talk, clicks for blind dialing</td></tr>
<tr><td>Wind brackets (e.g. 5 / 10 mph full value)</td><td>Your wind call picks a column; scale linearly in between</td></tr>
<tr><td>Transonic / limit marked</td><td>Tells you where the data stops being trustworthy</td></tr>
<tr><td>Big, high-contrast font</td><td>Readable in bad light through a scope-cap window</td></tr>
</tbody></table>`,
        quiz: [
          { q: 'Why use 25 yd steps past ~600 yd?', options: ['Looks neater', 'Elevation changes faster than linear interpolation tracks', 'Rangefinders round to 25'], answer: 1, why: 'The curve is convex; wide steps make interpolation error larger far out.' },
        ],
      },
      {
        id: 'wind-formats',
        title: 'Wind on the card: brackets and shortcuts',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> Elevation is one number per range; wind needs a <b>scalable</b> format because speed and direction keep changing.
Store a reference wind, then scale: <code>hold = ref_hold × (speed / ref_speed) × value(clock)</code>.</div>
<table class="tbl text">
<thead><tr><th>Format</th><th>How</th><th>Pros / cons</th></tr></thead>
<tbody>
<tr><td>Bracket columns</td><td>Holds for 5 / 10 / 15 mph full value at each range</td><td>No math; wide card</td></tr>
<tr><td>Single 10 mph column</td><td>One reference; scale linearly</td><td>Compact; light mental math</td></tr>
<tr><td>"mph per mil"</td><td>At each range: the full-value wind speed that needs 1.0 mil</td><td>Hold = wind ÷ that number; very compact, needs division</td></tr>
<tr><td>Rule-of-thumb constants</td><td>A single formula for all ranges</td><td>Works only over a limited band; verify against your solver</td></tr>
</tbody></table>
<div class="callout warn"><b>Exception:</b> all formats assume drift is linear in wind speed, which holds well. They do <i>not</i> capture spin drift
(always the same direction) — add it as a fixed offset or include it in the column.</div>`,
        quiz: [
          { q: 'Card: 10 mph full value = 1.4 mil at 800. Call: 7 mph from 2 o\'clock. Hold ≈', options: ['0.85 mil right', '1.4 mil right', '0.5 mil left'], answer: 0, why: '1.4 × 0.7 × 0.87 ≈ 0.85; wind from the right → hold right.' },
        ],
      },
      {
        id: 'truing',
        title: 'Truing: making the model match reality',
        mins: 6,
        html: `
<div class="callout rule"><b>Rule:</b> True <b>muzzle velocity first</b> using impacts in the supersonic region, then adjust <b>BC / drop scale factor</b>
using impacts near the transonic region. Change one input at a time.</div>
<ol class="steps">
<li>Confirm zero and scope tracking (tall target test) — otherwise you'll "fix" the wrong thing.</li>
<li>Shoot groups at a known range where the bullet is still well supersonic (e.g. 600–800 yd for a 6.5 CM). Measure the real elevation needed.</li>
<li>Change MV in the solver until its elevation at that range matches. Small MV changes move far elevation.</li>
<li>Shoot near the transonic range. If it still disagrees, adjust BC (or the solver's drop-scale/DSF) for that band.</li>
<li>Re-print the card and note what you changed and when.</li>
</ol>
<div class="callout warn"><b>Exception:</b> don't true in gusty conditions or from single shots. Use group centers, measured ranges, and record DA.</div>
<div class="callout try"><b>Verify:</b> turn on "Hidden MV error" on the <a data-goto="range">Range</a>. Find the error with impacts, then fix MV on Build Card until the card matches.</div>`,
        quiz: [
          { q: 'Your 800 yd impacts are consistently 0.3 mil low vs the card. Most likely fix first?', options: ['Lower the MV in the solver', 'Raise BC', 'Change the zero'], answer: 0, why: 'Low impacts at supersonic ranges usually mean the real MV is lower than entered.' },
        ],
      },
      {
        id: 'conditions',
        title: 'Conditions: DA bands, temperature, angle, cold bore',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> A card is valid for the conditions on its header. When conditions change, either <b>switch card</b> (DA bands),
<b>recompute</b>, or <b>apply a known correction</b>.</div>
<table class="tbl text">
<thead><tr><th>Condition</th><th>What changes</th><th>Handling</th></tr></thead>
<tbody>
<tr><td>Density altitude</td><td>Drag</td><td>Cards for e.g. 0 / 3,000 / 6,000 ft DA, or recompute on the day</td></tr>
<tr><td>Ammo temperature</td><td>MV (temp sensitivity, 0.3–1.5 fps/°F)</td><td>Chrono at several temps; keep ammo out of direct sun</td></tr>
<tr><td>Shot angle</td><td>Gravity's component across the line of sight</td><td>Rifleman's rule: use range × cos(angle) for elevation (approximate)</td></tr>
<tr><td>Cold / clean bore</td><td>First shot may land differently</td><td>Record cold-bore impacts separately in your data book</td></tr>
</tbody></table>
<pre class="code">angle   cos    600 yd LOS → "shoot it as"
 10°   0.985   591 yd
 20°   0.940   564 yd
 30°   0.866   520 yd</pre>`,
        quiz: [
          { q: '700 yd line-of-sight at 25° downhill. Elevation is roughly that for…', options: ['700 yd', '635 yd', '770 yd'], answer: 1, why: 'cos(25°) ≈ 0.906 → about 634 yd. Uphill or downhill, it is less elevation.' },
          { q: 'Ammo baked in the sun will usually…', options: ['Hit low', 'Hit high (more MV)', 'Not change'], answer: 1, why: 'Hotter powder burns faster: higher MV, less drop.' },
        ],
      },
      {
        id: 'card-formats',
        title: 'Where the card lives & the data book',
        mins: 3,
        html: `
<div class="callout rule"><b>Rule:</b> Put the card where your eyes already are. If you have to break position to read it, it costs time and stability.</div>
<table class="tbl text">
<thead><tr><th>Location</th><th>Pros</th><th>Cons</th></tr></thead>
<tbody>
<tr><td>Scope cap / turret cap</td><td>Visible without moving</td><td>Small; elevation only</td></tr>
<tr><td>Stock / chassis panel</td><td>Bigger, both columns</td><td>Needs head movement</td></tr>
<tr><td>Wrist coach</td><td>Multiple cards (DA bands), stage notes</td><td>Arm movement</td></tr>
<tr><td>Ballistic app / rangefinder</td><td>Exact for today's conditions</td><td>Batteries, button presses, time</td></tr>
</tbody></table>
<p><b>Data book:</b> for every string record date, rifle, ammo lot, DA/temp, wind call, range, dial, impact and notes. It's how you true,
spot trends (barrel wear, lot changes) and learn wind.</p>`,
        quiz: [
          { q: 'Main purpose of a data book?', options: ['Scoring', 'Close the loop: compare predictions with impacts and conditions', 'Legal record'], answer: 1, why: 'Recorded impacts are what you true and improve your card with.' },
        ],
      },
    ],
  },
  // =====================================================================
  {
    id: 'gear',
    title: 'Gear: what to use',
    lessons: [
      {
        id: 'rifle',
        title: 'The rifle system',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> Long-range success is <b>consistency</b>: a rifle that returns to zero, fits you, and puts every shot in the
same place. Spend on barrel, optic and support before cosmetics.</div>
<table class="tbl text">
<thead><tr><th>Component</th><th>What matters</th><th>Typical choice</th></tr></thead>
<tbody>
<tr><td>Action</td><td>Rigid, consistent lockup, good feeding</td><td>Custom/semi-custom bolt actions or quality factory</td></tr>
<tr><td>Barrel</td><td>Precision, twist for your bullet, length for MV (22–26")</td><td>Match-grade stainless, 1:7.5–1:8 for 6/6.5 mm</td></tr>
<tr><td>Stock / chassis</td><td>Fit, adjustable cheek and length of pull, weight for stability</td><td>Chassis with ARCA rail for PRS</td></tr>
<tr><td>Trigger</td><td>Clean, consistent, 1.5–2.5 lb break</td><td>Adjustable single-stage</td></tr>
<tr><td>Muzzle device</td><td>Recoil reduction lets you spot your own impacts</td><td>Brake (loud) or suppressor (quiet, heavier)</td></tr>
<tr><td>Weight</td><td>Heavier = steadier, less recoil</td><td>14–18 lb for competition, lighter for hunting</td></tr>
</tbody></table>
<div class="callout tip">Being able to <b>see your own impact</b> is a huge skill multiplier. Low recoil + a brake/suppressor + solid position = self-spotting.</div>`,
        quiz: [
          { q: 'Why does low recoil matter beyond comfort?', options: ['Cheaper ammo', 'You can watch and spot your own impacts', 'Better BC'], answer: 1, why: 'Staying on target lets you correct your own misses without a spotter.' },
        ],
      },
      {
        id: 'optics-gear',
        title: 'Optics and mounts',
        mins: 4,
        html: `
<div class="callout rule"><b>Rule:</b> The scope must <b>track</b>, <b>return to zero</b> and <b>stay put</b>. Glass quality is nice; mechanical reliability is mandatory.</div>
<table class="tbl text">
<thead><tr><th>Feature</th><th>Precision recommendation</th></tr></thead>
<tbody>
<tr><td>Magnification</td><td>~4–25× or 5–30×; most shooting happens at 12–18×</td></tr>
<tr><td>Focal plane</td><td>FFP</td></tr>
<tr><td>Units</td><td>MIL reticle + MIL turrets (matched)</td></tr>
<tr><td>Turrets</td><td>0.1 mil clicks, zero stop, rev indicator, ≥ 25 mil total elevation</td></tr>
<tr><td>Tube</td><td>34 or 35 mm for more travel</td></tr>
<tr><td>Mount</td><td>One-piece or quality rings, canted (≈6 mil) base, torqued; bubble level on the scope</td></tr>
</tbody></table>`,
        quiz: [
          { q: 'Most important scope property for a dope card?', options: ['Max magnification', 'Accurate, repeatable tracking', 'Illumination'], answer: 1, why: 'A card assumes a click moves exactly what it says, every time.' },
        ],
      },
      {
        id: 'measure',
        title: 'Measurement tools',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> Every number on the card comes from a measurement. Better measurement tools = smaller errors = more first-round hits.</div>
<table class="tbl text">
<thead><tr><th>Tool</th><th>Measures</th><th>Notes</th></tr></thead>
<tbody>
<tr><td>Chronograph</td><td>MV, SD, ES</td><td>Doppler radar units (e.g. Garmin Xero, LabRadar) don't touch the rifle; optical screens need light; barrel-mounted magnetic units can shift POI</td></tr>
<tr><td>Laser rangefinder</td><td>Line-of-sight range, often angle</td><td>Beam divergence matters on small/far targets; many include a ballistic solver</td></tr>
<tr><td>Weather meter</td><td>Temp, station pressure, humidity, DA, wind at your position</td><td>Kestrel-style meters can run a full solver (e.g. Applied Ballistics)</td></tr>
<tr><td>Angle indicator</td><td>Shot inclination</td><td>Or use the rangefinder's angle</td></tr>
<tr><td>Bubble level</td><td>Cant</td><td>Mount where you can see it in position</td></tr>
<tr><td>Ballistic app</td><td>Solutions, card printing, truing</td><td>e.g. Applied Ballistics, Hornady 4DOF, Strelok</td></tr>
</tbody></table>
<div class="callout warn"><b>Exception:</b> your weather meter measures wind <i>where you are</i>. The bullet cares about the wind all the way to the target.</div>`,
        quiz: [
          { q: 'Why can a barrel-mounted chronograph be a problem?', options: ['It is inaccurate', 'It can change barrel harmonics and point of impact', 'It needs sunlight'], answer: 1, why: 'Anything clamped to the barrel may change how it vibrates.' },
        ],
      },
      {
        id: 'support',
        title: 'Support gear: bipods, bags, slings',
        mins: 3,
        html: `
<div class="callout rule"><b>Rule:</b> Stability is precision. The steadier the rifle, the smaller the wobble you have to fight at the moment the shot breaks.</div>
<table class="tbl text">
<thead><tr><th>Gear</th><th>Use</th></tr></thead>
<tbody>
<tr><td>Bipod</td><td>Prone foundation; load it forward slightly for consistency</td></tr>
<tr><td>Rear bag</td><td>Fine elevation control by squeezing; removes most wobble</td></tr>
<tr><td>Barricade / "game changer" style bags</td><td>Stable on props, rooftops, tank traps</td></tr>
<tr><td>Tripod with ARCA clamp</td><td>Standing/kneeling positions, spotting, hunting</td></tr>
<tr><td>Sling</td><td>Adds tension and stability in field positions</td></tr>
</tbody></table>
<div class="callout try"><b>Verify:</b> on the <a data-goto="range">Range</a>, change "Position" from prone + rear bag to kneeling and watch the reticle sway.</div>`,
        quiz: [
          { q: 'What most reduces reticle wobble in prone?', options: ['Rear bag', 'Higher magnification', 'Faster trigger pull'], answer: 0, why: 'Supporting the rear of the rifle removes most movement.' },
        ],
      },
    ],
  },
  // =====================================================================
  {
    id: 'ammo',
    title: 'Cartridges & ammunition',
    lessons: [
      {
        id: 'cartridges',
        title: 'Choosing a cartridge (rifle systems compared)',
        mins: 6,
        html: `
<div class="callout rule"><b>Rule:</b> Every cartridge is a trade-off between <b>wind performance</b> (BC + velocity), <b>recoil</b> (can you spot your hits?),
<b>barrel life</b> and <b>ammo cost/availability</b>. The table below is computed live by this app's solver at sea level, 10 mph full-value wind.</div>
<div data-widget="cartridge-table"></div>
<table class="tbl text">
<thead><tr><th>Category</th><th>Examples</th><th>Best for</th></tr></thead>
<tbody>
<tr><td>Trainer</td><td>.223 Rem, .308 Win</td><td>Cheap, long barrel life, teaches wind (they drift a lot)</td></tr>
<tr><td>PRS / competition</td><td>6mm Creedmoor, 6 Dasher/GT, 6.5 Creedmoor</td><td>Low recoil, high BC, self-spotting</td></tr>
<tr><td>Long range / hunting</td><td>6.5 PRC, .300 Win Mag, .300 PRC</td><td>More energy and less wind drift, more recoil</td></tr>
<tr><td>Extreme range</td><td>.338 Lapua, .375/.416 class</td><td>1,500+ yd, heavy rifles, expensive</td></tr>
</tbody></table>
<div class="callout tip">Use the "Rifle system" dropdown on <a data-goto="build">Build Card</a> to load any of these and see its full card.</div>`,
        quiz: [
          { q: 'Why do many PRS shooters use 6 mm cartridges?', options: ['Most energy', 'Low recoil (self-spotting) with high BC', 'Longest barrel life'], answer: 1, why: 'Low recoil keeps you on target to spot hits, while high-BC 6 mm bullets still buck wind well.' },
          { q: 'Why is .308 Win a good learning cartridge?', options: ['It drifts the least', 'Cheap, long barrel life, and its wind drift punishes bad calls', 'It never goes transonic'], answer: 1, why: 'It is forgiving on the wallet and the barrel, and teaches wind reading.' },
        ],
      },
      {
        id: 'bullets',
        title: 'Bullet types and construction',
        mins: 6,
        html: `
<div class="callout rule"><b>Rule:</b> For long range you want a bullet that is <b>consistent</b> (every bullet flies the same), <b>low drag</b> (high BC) and
<b>stable</b> in your twist. Terminal performance only matters for hunting.</div>
<table class="tbl text">
<thead><tr><th>Type</th><th>What it is</th><th>Strengths</th><th>Watch out</th></tr></thead>
<tbody>
<tr><td>OTM / HPBT match</td><td>Open-tip match, hollow point from jacket forming, boat tail</td><td>Very consistent, the precision standard</td><td>Open tip is not designed to expand</td></tr>
<tr><td>Secant ogive (VLD)</td><td>Very sharp nose profile</td><td>Highest BC</td><td>Sensitive to seating depth (jump)</td></tr>
<tr><td>Tangent ogive</td><td>Gentle nose curve</td><td>Forgiving of seating depth</td><td>Lower BC</td></tr>
<tr><td>Hybrid ogive</td><td>Tangent near the bearing surface, secant at the front</td><td>High BC <i>and</i> forgiving</td><td>Longer — needs twist</td></tr>
<tr><td>Polymer / aluminum tip</td><td>Tip closes the meplat (e.g. ELD-M, A-Tip style)</td><td>More uniform BC bullet to bullet</td><td>—</td></tr>
<tr><td>Monolithic (copper/brass)</td><td>Solid, lathe-turned</td><td>Uniform, lead-free, high BC designs</td><td>Long for weight → fast twist; different pressure</td></tr>
<tr><td>FMJ boat tail</td><td>Military ball</td><td>Cheap</td><td>Less consistent; poor long-range precision</td></tr>
<tr><td>Hunting (bonded, expanding)</td><td>Designed to expand/retain weight</td><td>Ethical terminal effect</td><td>Check minimum expansion velocity at your max range</td></tr>
</tbody></table>
<div class="callout tip"><b>Boat tail vs flat base:</b> boat tails reduce drag at long range; flat base bullets can be marginally more precise at short range.</div>`,
        quiz: [
          { q: 'Why does a polymer tip help consistency?', options: ['It expands', 'It makes the nose (meplat) uniform, so BC varies less', 'It adds weight'], answer: 1, why: 'Hollow-point meplats vary; a tip removes that variation.' },
          { q: 'A long monolithic bullet usually needs…', options: ['A slower twist', 'A faster twist', 'Same twist as lead-core of equal weight'], answer: 1, why: 'Copper is less dense, so it is longer for its weight, and length drives required twist.' },
        ],
      },
      {
        id: 'consistency',
        title: 'Ammo consistency: SD, ES, lots',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> Velocity variation becomes <b>vertical dispersion</b> at distance. Standard deviation (SD) is the number that predicts it;
extreme spread (ES) depends on how many shots you fired.</div>
<div data-widget="sd-calc"></div>
<table class="tbl text">
<thead><tr><th>SD (fps)</th><th>Typical source</th><th>Long-range verdict</th></tr></thead>
<tbody>
<tr><td>&lt; 6</td><td>Excellent handloads</td><td>Ideal for 1,000+ yd</td></tr>
<tr><td>6 – 10</td><td>Good handloads / premium match factory</td><td>Very good</td></tr>
<tr><td>10 – 15</td><td>Most match factory ammo</td><td>Fine to ~800 yd, visible vertical beyond</td></tr>
<tr><td>&gt; 15</td><td>Bulk / non-match</td><td>Expect vertical stringing</td></tr>
</tbody></table>
<div class="callout warn"><b>Exception:</b> a 5-shot SD is a very noisy estimate. Use 10–20 shots before you believe a number. And re-chrono every new ammo <b>lot</b>.</div>`,
        quiz: [
          { q: 'What does muzzle-velocity SD become at long range?', options: ['Horizontal spread', 'Vertical spread', 'Nothing'], answer: 1, why: 'Faster bullets drop less, slower drop more: vertical stringing.' },
        ],
      },
      {
        id: 'powder-barrel',
        title: 'Powder temperature and barrel life',
        mins: 4,
        html: `
<div class="callout rule"><b>Rule:</b> Powder burns faster when warm, so <b>MV rises with ammo temperature</b>. A temp-stable powder may change 0.3 fps/°F;
a sensitive one 1.5 fps/°F or more.</div>
<pre class="code">MV_today = MV_chrono + sensitivity × (ammo_temp − chrono_temp)
example: 2710 + 0.8 × (95 − 59) = 2739 fps   → ≈ 0.1 mil less at 800 yd</pre>
<ul>
<li>Keep ammo in the shade — a round sitting in a hot chamber or in the sun can be 30°F+ hotter than the air.</li>
<li>Chronograph at two temperatures to measure your sensitivity, then enter it in your solver.</li>
</ul>
<h4>Barrel life</h4>
<p>Hot, high-capacity cartridges in small bores erode the throat fastest. As the throat wears, MV usually drops and you must re-chrono.
Rough accuracy life: <b>.223/.308: 5,000+</b> · <b>6.5 CM: 2,500–3,500</b> · <b>6mm CM: 2,000–3,000</b> · <b>6.5 PRC / .300 magnums: 1,500–2,500</b>. Varies widely.</p>`,
        quiz: [
          { q: 'Ammo chronographed at 59°F is shot at 95°F with 1 fps/°F sensitivity. MV changes by…', options: ['+36 fps', '−36 fps', '0'], answer: 0, why: '1 × (95 − 59) = +36 fps.' },
        ],
      },
    ],
  },
  // =====================================================================
  {
    id: 'field',
    title: 'Field craft: tips & tricks',
    lessons: [
      {
        id: 'read-wind',
        title: 'Reading the wind',
        mins: 6,
        html: `
<div class="callout rule"><b>Rule:</b> Gather every indicator between you and the target, weight the ones where the bullet spends most time,
call a <b>bracket</b>, and hold for it. Then use the impact to refine.</div>
<h4>Vegetation & terrain</h4>
<table class="tbl text">
<thead><tr><th>Speed</th><th>What you see</th></tr></thead>
<tbody>
<tr><td>0 – 3 mph</td><td>Barely felt; smoke drifts</td></tr>
<tr><td>3 – 5 mph</td><td>Felt on the face; leaves rustle</td></tr>
<tr><td>5 – 8 mph</td><td>Leaves and small twigs in constant motion</td></tr>
<tr><td>8 – 12 mph</td><td>Dust and loose paper lift; small branches move</td></tr>
<tr><td>12 – 15+ mph</td><td>Small trees sway; mirage disappears</td></tr>
</tbody></table>
<h4>Mirage</h4>
<table class="tbl text">
<thead><tr><th>Mirage</th><th>Means</th></tr></thead>
<tbody>
<tr><td>Boiling straight up</td><td>No crosswind (calm, or head/tail wind) — or a let-off about to reverse</td></tr>
<tr><td>Slight lean</td><td>~1–4 mph</td></tr>
<tr><td>Running flat</td><td>~8–12 mph</td></tr>
<tr><td>Gone</td><td>~12+ mph, or no heat</td></tr>
</tbody></table>
<ul>
<li>Focus the scope's parallax slightly in front of the target to see mid-range mirage.</li>
<li>Flags: a common estimate is <b>flag angle (deg from the pole) ÷ 4 ≈ mph</b>.</li>
<li>Watch for <b>switches</b> (flags reversing) — wait them out or hold for the new side.</li>
<li>Hold for the <b>edge</b> of the plate on the side the wind comes from when you are unsure of the speed.</li>
</ul>
<div class="callout try"><b>Verify:</b> the <a data-goto="range">Range</a> in Realistic mode gives no wind call — only flags, mirage and a meter at your position.</div>`,
        quiz: [
          { q: 'Mirage running flat usually means about…', options: ['0–2 mph', '8–12 mph', '25 mph'], answer: 1, why: 'Flat running mirage means a solid wind; above ~12 mph it tends to disappear.' },
          { q: 'Boiling mirage suggests…', options: ['Strong crosswind', 'No crosswind (or a switch coming)', 'Rain'], answer: 1, why: 'Heat rises straight up when nothing pushes it sideways.' },
        ],
      },
      {
        id: 'shot-process',
        title: 'The shot process',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> Most "wind" misses at short range are actually <b>shooter</b> misses. A repeatable shot process removes your
own error so the data and the wind call can be judged honestly.</div>
<ol class="steps">
<li><b>Build the position</b> — bone support, not muscle. Rifle loaded straight back into the shoulder.</li>
<li><b>Natural point of aim</b> — close your eyes, breathe, open: if the reticle drifted, move your body, not your arms.</li>
<li><b>Dial, level, check parallax.</b></li>
<li><b>Breathe</b> — settle in the natural respiratory pause. Don't hold too long: after ~5–8 s, oxygen debt makes the wobble grow.</li>
<li><b>Press</b> the trigger straight back while the reticle is in its smallest wobble area.</li>
<li><b>Follow through and call the shot</b> — where was the reticle when it broke? Watch for the impact.</li>
</ol>
<div class="callout try"><b>Verify:</b> the <a data-goto="range">Range</a> sways with your position and breathing. Hold <kbd>B</kbd> to hold your breath — and don't hold it too long.</div>`,
        quiz: [
          { q: 'Holding your breath for 15 seconds before the shot…', options: ['Steadies you more', 'Increases wobble from oxygen debt', 'Has no effect'], answer: 1, why: 'Short pauses help; long holds make you shake.' },
        ],
      },
      {
        id: 'corrections',
        title: 'Spotting and corrections',
        mins: 5,
        html: `
<div class="callout rule"><b>Rule:</b> A miss is <b>data</b>. Measure where it hit in the reticle, and correct by the opposite amount — if you trust the shot.</div>
<pre class="code">new_dial = old_dial − impact_offset
impact 0.3 low  → dial 0.3 more UP
impact 0.2 left → hold/dial 0.2 more RIGHT</pre>
<table class="tbl text">
<thead><tr><th>Situation</th><th>Do</th></tr></thead>
<tbody>
<tr><td>Clean shot, steady wind, big miss</td><td>Full correction</td></tr>
<tr><td>Wind changed after the shot</td><td>Correct for the new wind, not the impact</td></tr>
<tr><td>Bad shot (you pulled it)</td><td>Don't correct — the data didn't miss, you did</td></tr>
<tr><td>Consistent vertical across targets</td><td>Card/DA/MV issue — true the card</td></tr>
</tbody></table>
<p>Spotter call order is usually <b>elevation then wind</b>: "Up 0.3, right 0.2" or "Hit".</p>`,
        quiz: [
          { q: 'Impact 0.4 mil high and 0.1 mil right with 5.0 mil dialed. New elevation?', options: ['5.4', '4.6', '5.0'], answer: 1, why: 'It hit high, so dial down 0.4 → 4.6.' },
        ],
      },
      {
        id: 'stages',
        title: 'Positions and PRS-style stages',
        mins: 4,
        html: `
<div class="callout rule"><b>Rule:</b> Under a clock, the winners are the shooters who <b>plan</b> before the buzzer: dope, wind holds and target order written down,
positions rehearsed, and a rule for when to skip a target.</div>
<ul>
<li>Write a <b>stage card</b>: target, range, elevation, wind hold, position.</li>
<li>Dial for the farthest target and <b>hold</b> under for closer ones (or dial each if time allows).</li>
<li>Time budget: e.g. 2 min for 10 shots = 12 s per shot including transitions.</li>
<li>If you miss twice on a target, decide in advance whether to move on.</li>
<li>Prone is the most stable; barricades and props reward practice with bags.</li>
</ul>
<div class="callout try"><b>Verify:</b> run a timed <b>Stage</b> on the <a data-goto="range">Range</a>.</div>`,
        quiz: [
          { q: 'Best time to work out your dope for a stage?', options: ['After the buzzer', 'Before the buzzer, written on a stage card', 'Never, use the reticle'], answer: 1, why: 'Doing the math beforehand turns the timed run into execution only.' },
        ],
      },
      {
        id: 'mistakes',
        title: 'Common mistakes checklist',
        mins: 3,
        html: `
<div class="callout rule"><b>Rule:</b> Most misses come from a short list of procedural errors. Check them in order before blaming the wind.</div>
<table class="tbl text">
<thead><tr><th>Mistake</th><th>Symptom</th></tr></thead>
<tbody>
<tr><td>Wrong turret revolution</td><td>Miss by exactly one revolution (e.g. 10 mil)</td></tr>
<tr><td>Dialed the wrong direction</td><td>Miss by twice the intended correction</td></tr>
<tr><td>Didn't return to zero</td><td>Next stage starts with old elevation</td></tr>
<tr><td>App or card set to the wrong unit</td><td>Miss by a factor of ~3.4</td></tr>
<tr><td>Wrong card / DA band</td><td>Consistent high or low</td></tr>
<tr><td>Cant</td><td>Sideways misses that grow with elevation</td></tr>
<tr><td>Parallax not set</td><td>Random-looking misses that change with head position</td></tr>
<tr><td>SFP reticle used for holds at the wrong power</td><td>Holds too big or too small</td></tr>
<tr><td>Wind called for your position only</td><td>Misses on the downrange wind side</td></tr>
</tbody></table>`,
        quiz: [
          { q: 'You miss exactly 10 mil low at 1,100 yd. Most likely?', options: ['Wind', 'One turret revolution off', 'Bad ammo'], answer: 1, why: 'A miss of exactly one revolution is the signature of the rev error.' },
        ],
      },
    ],
  },
  // =====================================================================
  {
    id: 'glossary',
    title: 'Glossary',
    lessons: [
      { id: 'terms', title: 'Terms A–Z', mins: 0, html: '<div data-widget="glossary"></div>' },
    ],
  },
];

window.LRPS_GLOSSARY = [
  ['Aerodynamic jump', 'Vertical deflection caused by a crosswind acting on the spinning bullet as it leaves the muzzle.'],
  ['ARCA rail', 'Dovetail rail standard for quickly clamping a rifle to tripods and bags.'],
  ['BC (ballistic coefficient)', 'How well a bullet overcomes drag relative to a reference projectile (G1/G7). Higher = less drag.'],
  ['Bracket', 'A range of wind speeds you believe the wind is within; you hold for its middle or an edge.'],
  ['Cant', 'Rotation of the rifle around the bore axis. Causes sideways misses proportional to dialed elevation.'],
  ['Cold bore', 'The first shot from a cold, often clean barrel; may impact differently.'],
  ['Coriolis effect', 'Apparent deflection from the Earth rotating during the bullet flight.'],
  ['DA (density altitude)', 'Altitude in the standard atmosphere with the same air density as current conditions.'],
  ['Dial / hold', 'Dial = move the turrets; hold = aim off using the reticle.'],
  ['DOPE', 'Data On Previous Engagements: your recorded firing solutions.'],
  ['Drag model', 'Reference drag curve (G1, G7) that a BC scales.'],
  ['ES (extreme spread)', 'Fastest minus slowest velocity in a string. Grows with the number of shots.'],
  ['FFP / SFP', 'First / second focal plane: whether reticle subtensions scale with magnification.'],
  ['Full value', 'A wind blowing straight across the line of fire (3 or 9 o\'clock).'],
  ['Lag time', 'Actual time of flight minus the vacuum time of flight; drives wind drift.'],
  ['Mach', 'Speed relative to the speed of sound (~1,120 fps, varies with temperature).'],
  ['Meplat', 'The tip of the bullet; its uniformity affects BC consistency.'],
  ['MIL / mrad', 'Milliradian: 3.6 in at 100 yd, 10 cm at 100 m.'],
  ['Mirage', 'Visible heat shimmer; its direction and angle show the wind.'],
  ['MOA', 'Minute of angle, ≈ 0.29 mil. An older angular unit; this app uses MIL only.'],
  ['MV', 'Muzzle velocity.'],
  ['NPA', 'Natural point of aim: where the rifle points when your body is relaxed.'],
  ['Ogive', 'The curved nose section of a bullet (tangent, secant, hybrid).'],
  ['Parallax', 'Apparent movement of the reticle against the target when the eye moves; removed by focusing.'],
  ['SD (standard deviation)', 'Statistical spread of muzzle velocity; predicts vertical dispersion.'],
  ['Sg', 'Gyroscopic stability factor (Miller formula). Aim for 1.4–1.5+.'],
  ['Spin drift', 'Drift in the direction of rifling twist, growing with time of flight.'],
  ['Station pressure', 'Actual barometric pressure at your location (not sea-level corrected).'],
  ['Tall target test', 'Verifying that scope adjustments move exactly the labeled amount.'],
  ['Transonic', 'Roughly Mach 0.8–1.2, where drag changes rapidly and predictions degrade.'],
  ['Truing', 'Adjusting solver inputs (MV, BC/DSF) until predictions match observed impacts.'],
  ['Twist rate', 'Barrel length per full turn of rifling, e.g. 1:8 = one turn in 8 inches.'],
  ['Zero stop', 'A mechanical stop that lets the turret return to zero without looking.'],
];
